replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/accounts
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

config: {}

service:
  ports:
    grpc: 5001

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 400m
   memory: 1000Mi
  requests:
   cpu: 400m
   memory: 1000Mi

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-accounts"
  vault.hashicorp.com/agent-inject-secret-common: "videocoin/v1/networks/everest-dev/console/common"
  vault.hashicorp.com/agent-inject-secret-config: "videocoin/v1/networks/everest-dev/console/accounts"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/common" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/accounts" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
