replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/accounts
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5001
  internalRpcPort: 5001

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 200m
   memory: 200Mi
  requests:
   cpu: 200m
   memory: 200Mi

secrets:
  dbUri: ""
  mqUri: ""
  secret: ""
  sentryDsn: ""

