replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/accounts
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

config: {}

service:
  ports:
    grpc: 5001

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 400m
   memory: 1000Mi
  requests:
   cpu: 400m
   memory: 1000Mi

secrets:
  dbUri: "cm9vdDpacUFEZWNYc3czMTJAKG15c3FsOjMzMDYpL2NvbnNvbGU/Y2hhcnNldD11dGY4JnBhcnNlVGltZT1UcnVlJmxvYz1Mb2NhbA=="
  mqUri: "YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLWhhLmNvbnNvbGUuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg=="
  clientSecret: "c2VjcmV0"
  sentryDsn: ""
